name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        miniforge-version: latest
        activate-environment: oa-tools
        environment-file: oa_tools_lock.yml
        use-mamba: true
    
    - name: Cache conda environment
      uses: actions/cache@v4
      with:
        path: /usr/share/miniconda3/envs/oa-tools
        key: conda-${{ runner.os }}-${{ hashFiles('oa_tools_lock.yml') }}
        restore-keys: |
          conda-${{ runner.os }}-
          
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        conda activate oa-tools
        uv sync --extra dev
    
    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate oa-tools
        uv run pytest -v -m "not requires_aws"